# Generated by Django 6.0.4 on 2026-04-16 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('original_title', models.CharField(blank=True, max_length=200, verbose_name='Оригинальное название')),
                ('season', models.PositiveSmallIntegerField(verbose_name='Сезон')),
                ('episode_number', models.PositiveSmallIntegerField(verbose_name='Номер серии')),
                ('air_date', models.DateField(verbose_name='Дата выхода')),
                ('short_description', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('description', models.TextField(blank=True, verbose_name='Полное описание')),
                ('director', models.CharField(blank=True, max_length=100)),
                ('writer', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Эпизод',
                'verbose_name_plural': 'Эпизоды',
                'ordering': ['season', 'episode_number'],
            },
        ),
    ]
