# Generated by Django 6.0.4 on 2026-04-16 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('x_files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Показывать на главной'),
        ),
        migrations.AddField(
            model_name='episode',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Рейтинг IMDb (0–10)'),
        ),
    ]
