# Generated by Django 6.0.4 on 2026-04-18 03:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('x_files', '0002_episode_is_featured_episode_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('slug', models.SlugField(help_text='Автоматически формируется из заголовка', max_length=200, unique=True, verbose_name='URL')),
                ('summary', models.TextField(help_text='Отображается на главной странице', max_length=500, verbose_name='Краткое содержание')),
                ('content', models.TextField(verbose_name='Полный текст новости')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news_images/', verbose_name='Изображение')),
                ('author', models.CharField(default='Редакция', max_length=100, verbose_name='Автор')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-published_at'],
            },
        ),
    ]
