# Generated by Django 6.0.4 on 2026-04-16 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('x_files', '0002_episode_is_featured_episode_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('status', models.CharField(blank=True, max_length=50, verbose_name='Статус')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='characters/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Персонаж',
                'verbose_name_plural': 'Персонажи',
            },
        ),
    ]
