# Generated by Django 6.0.4 on 2026-04-18 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('x_files', '0003_character'),
        ('x_files', '0003_news'),
    ]

    operations = [
    ]
