# Generated by Django 6.0.4 on 2026-04-18 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('x_files', '0003_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='imdb_url',
            field=models.URLField(blank=True, max_length=100, null=True, verbose_name='Ссылка на IMDb'),
        ),
    ]
