# Generated by Django 6.0.4 on 2026-04-18 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('x_files', '0004_episode_imdb_url'),
        ('x_files', '0004_merge_0003_character_0003_news'),
    ]

    operations = [
    ]
