# Generated by Django 6.0.4 on 2026-04-18 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('x_files', '0005_merge_20260418_1014'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={},
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='character',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='characters/'),
        ),
        migrations.AlterField(
            model_name='character',
            name='status',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
