# Generated by Django 6.0.4 on 2026-04-22 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('x_files', '0006_alter_character_options_alter_character_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('image', models.ImageField(upload_to='gallery/%Y/%m/', verbose_name='Изображение')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Галерея',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
